### ISSUE TITLE
a bug in counting total_comparisons/prompt_tokens/completion_tokens

### ISSUE THREAD

**Issue by Ziyang1060** [ielab/llm-rankers#1]
https://github.com/ielab/llm-rankers/blob/4f632a41f688ce2ad81040dd66327ae67d85a877/run.py#L193C2-L195C66
I may have found a bug in counting total_comparisons/prompt_tokens/completion_tokens. ranker.total_compare represents the cumulative number of calls to the ranker compare function, so there is no need to set total_comparisons in the run.py file to re-accumulate.

**Comment by Ziyang1060** [comment]
Ok, I see the rerank function code with `self.total_compare = 0`. There doesn't appear to be any bugs in it.

**Comment by guidozuc** [comment]
Thanks @Ziyang1060 for checking this out.
